import type { Task } from './types'

export const upcomingTasksMock: Task[] = [
  {
    id: 'ui-kit',
    title: 'Собрать UI-kit проекта',
    space: 'Редизайн сайта',
    progress: 75,
    coverTone: 'primary',
    status: 'todo',
    priority: 'high',
    tag: 'Дизайн',
    comments: 3,
    assignee: 'ЕК',
    deadline: '2026-08-18',
  },
  {
    id: 'landing',
    title: 'Подготовить главную страницу',
    space: 'Мобильное приложение',
    progress: 85,
    coverTone: 'warning',
    status: 'in-progress',
    priority: 'medium',
    tag: 'Разработка',
    comments: 2,
    assignee: 'АМ',
    deadline: '2026-08-19',
  },
]

export const tasksMock: Task[] = [
  ...upcomingTasksMock,
  {
    id: 'research',
    title: 'Исследовать конкурентов',
    space: 'Редизайн сайта',
    progress: 30,
    coverTone: 'warning',
    status: 'backlog',
    priority: 'high',
    tag: 'Исследование',
    comments: 2,
    assignee: 'АМ',
    deadline: '2026-08-15',
  },
  {
    id: 'mobile-flow',
    title: 'Продумать сценарии приложения',
    space: 'Мобильное приложение',
    progress: 60,
    coverTone: 'primary',
    status: 'todo',
    priority: 'medium',
    tag: 'UX',
    comments: 4,
    assignee: 'МИ',
    deadline: '2026-08-17',
  },
  {
    id: 'adaptive',
    title: 'Сверстать адаптив главной',
    space: 'Редизайн сайта',
    progress: 45,
    coverTone: 'primary',
    status: 'in-progress',
    priority: 'medium',
    tag: 'Вёрстка',
    comments: 1,
    assignee: 'ЕК',
    deadline: '2026-08-20',
  },
  {
    id: 'site-audit',
    title: 'Анализ текущего сайта',
    space: 'Редизайн сайта',
    progress: 100,
    coverTone: 'warning',
    status: 'done',
    priority: 'low',
    tag: 'Исследование',
    comments: 2,
    assignee: 'АМ',
    deadline: '2026-08-12',
  },
  {
    id: 'auth',
    title: 'Настроить авторизацию',
    space: 'Мобильное приложение',
    progress: 15,
    coverTone: 'primary',
    status: 'backlog',
    priority: 'high',
    tag: 'Разработка',
    comments: 5,
    assignee: 'МИ',
    deadline: '2026-08-22',
  },
  {
    id: 'concept',
    title: 'Утвердить концепцию дизайна',
    space: 'Редизайн сайта',
    progress: 100,
    coverTone: 'warning',
    status: 'done',
    priority: 'low',
    tag: 'Дизайн',
    comments: 1,
    assignee: 'ЕК',
    deadline: '2026-08-10',
  },
]
